version: "3.9"


services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  sm_postgres:
    image: postgres:15
    container_name: sm_postgres
    volumes:
      - ~/.pg/pg_data/sm:/var/lib/postgresql/data
    env_file:
      - .env

  sitemotorcycles:
      image: sm_docker:latest
      container_name: sm_django
      depends_on:
        - sm_postgres
      network_mode: host
      volumes:
        - static_volume:/sm/static
        - media_volume:/sm/media
      env_file:
        - .env
      command: >
          bash -c " ./manage.py migrate
          && python manage.py runserver "
volumes:
  static_volume:
  media_volume:
  cache:
    driver: local
